### ISSUE TITLE
Remove TRY_Grtsk

### ISSUE THREAD

**Issue by davelab6** [BlackFoundryCom/black-robo-cjk#95]
https://github.com/BlackFoundryCom/black-robo-cjk/blob/master/manual/fonts/TRY_Grtsk%20Variable.ttf is probably not meant to be GPLv3. 

I suggest using the Google Fonts API for web fonts for this manual.

**Comment by GaetanBaehr** [comment]
Hello Dave, yes that's right, I changed it for IBM plex mono 1a6dd484fcb7f187224b1d32eff4faa1657f04f1
